In [2]:
import pandas as pd
import json
import requests

In [3]:
response = requests.get('https://firestore.googleapis.com/v1/projects/oeskb-app/databases/(default)/documents/saisonen/1_8_2024_2025/schnittliste/1_8_2024_2025H')
data = response.json()
print(json.dumps(data, indent=2))

{
  "name": "projects/oeskb-app/databases/(default)/documents/saisonen/1_8_2024_2025/schnittliste/1_8_2024_2025H",
  "fields": {
    "spiele": {
      "mapValue": {
        "fields": {
          "nKW1HmZZWos39zWU3lhW": {
            "mapValue": {
              "fields": {
                "heim": {
                  "mapValue": {
                    "fields": {
                      "teamName": {
                        "stringValue": "KSV Wien"
                      },
                      "vereinsNr": {
                        "stringValue": "19113"
                      },
                      "vereinsName": {
                        "stringValue": "KSV Wien"
                      },
                      "spieler": {
                        "mapValue": {
                          "fields": {
                            "HFdZhWlRyDDgubstJkvF": {
                              "mapValue": {
                                "fields": {
                                  "gegner": {
                                    "stringValue": "KOZAK Jennifer (607)"
                                  },
                                  "kegel": {
                                    "integerValue": "539"
                                  },
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "akJahr": {
                                    "integerValue": "2002"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "name": {
                                    "stringValue": "196408 / NIKOLIC Maja Katharina"
                                  },
                                  "bahn": {
                                    "integerValue": "1"
                                  },
                                  "dg": {
                                    "integerValue": "1"
                                  },
                                  "akHJ": {
                                    "integerValue": "1"
                                  },
                                  "sp": {
                                    "integerValue": "0"
                                  }
                                }
                              }
                            },
                            "ThGHwnyCP2jPnqAHQ9yA": {
                              "mapValue": {
                                "fields": {
                                  "name": {
                                    "stringValue": "196074 / PYCHOVA Barbora"
                                  },
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "sp": {
                                    "integerValue": "2"
                                  },
                                  "dg": {
                                    "integerValue": "3"
                                  },
                                  "bahn": {
                                    "integerValue": "1"
                                  },
                                  "gegner": {
                                    "stringValue": "BAUMGARTNER Mia-Laura (534)"
                                  },
                                  "kegel": {
                                    "integerValue": "550"
                                  },
                                  "akJahr": {
                                    "integerValue": "2001"
                                  },
                                  "land": {
                                    "stringValue": "CZE"
                                  },
                                  "mp": {
                                    "integerValue": "1"
                                  }
                                }
                              }
                            },
                            "yn7rbBEZboGdDw5IfFoM": {
                              "mapValue": {
                                "fields": {
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "kegel": {
                                    "integerValue": "588"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "sp": {
                                    "integerValue": "1"
                                  },
                                  "dg": {
                                    "integerValue": "3"
                                  },
                                  "gegner": {
                                    "stringValue": "STEINER Fiona (586)"
                                  },
                                  "bahn": {
                                    "integerValue": "3"
                                  },
                                  "name": {
                                    "stringValue": "196054 / LAIBACHER Marina"
                                  },
                                  "akJahr": {
                                    "integerValue": "1996"
                                  }
                                }
                              }
                            },
                            "Sm7t0cDy51j4jJuGBKDi": {
                              "mapValue": {
                                "fields": {
                                  "bahn": {
                                    "integerValue": "3"
                                  },
                                  "name": {
                                    "stringValue": "196411 / ST\u00d6CKL Sandra"
                                  },
                                  "sp": {
                                    "integerValue": "1"
                                  },
                                  "akJahr": {
                                    "integerValue": "2006"
                                  },
                                  "dg": {
                                    "integerValue": "2"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "gegner": {
                                    "stringValue": "NGUYEN Monika (558)"
                                  },
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "kegel": {
                                    "integerValue": "568"
                                  }
                                }
                              }
                            },
                            "6tFoI6m2UVaXWO2kYZsm": {
                              "mapValue": {
                                "fields": {
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "sp": {
                                    "integerValue": "0"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "kegel": {
                                    "integerValue": "608"
                                  },
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "name": {
                                    "stringValue": "196070 / ANGENBAUER Angelika"
                                  },
                                  "gegner": {
                                    "stringValue": "HARI Boglarka (648)"
                                  },
                                  "dg": {
                                    "integerValue": "1"
                                  },
                                  "akJahr": {
                                    "integerValue": "1991"
                                  },
                                  "bahn": {
                                    "integerValue": "3"
                                  }
                                }
                              }
                            },
                            "Magkqg6g3Sjmz6dg5KLv": {
                              "mapValue": {
                                "fields": {
                                  "bahn": {
                                    "integerValue": "1"
                                  },
                                  "dg": {
                                    "integerValue": "2"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "sp": {
                                    "integerValue": "0"
                                  },
                                  "gegner": {
                                    "stringValue": "SAJKO Eva (610)"
                                  },
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "akJahr": {
                                    "integerValue": "2002"
                                  },
                                  "name": {
                                    "stringValue": "196409 / PR\u00d6LL Tanja"
                                  },
                                  "kegel": {
                                    "integerValue": "555"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "gast": {
                  "mapValue": {
                    "fields": {
                      "vereinsName": {
                        "stringValue": "SK FWT-Comp. Neunkirchen"
                      },
                      "vereinsNr": {
                        "stringValue": "13117"
                      },
                      "spieler": {
                        "mapValue": {
                          "fields": {
                            "fta996CaW1i1aAqyVwLs": {
                              "mapValue": {
                                "fields": {
                                  "gegner": {
                                    "stringValue": "PR\u00d6LL Tanja (555)"
                                  },
                                  "akJahr": {
                                    "integerValue": "1985"
                                  },
                                  "mp": {
                                    "integerValue": "1"
                                  },
                                  "name": {
                                    "stringValue": "136130 / SAJKO Eva"
                                  },
                                  "kegel": {
                                    "integerValue": "610"
                                  },
                                  "land": {
                                    "stringValue": "SLO"
                                  },
                                  "dg": {
                                    "integerValue": "2"
                                  },
                                  "sp": {
                                    "integerValue": "4"
                                  },
                                  "akHJ": {
                                    "integerValue": "1"
                                  },
                                  "bahn": {
                                    "integerValue": "2"
                                  }
                                }
                              }
                            },
                            "OFC6r2ND621BArdiuyzl": {
                              "mapValue": {
                                "fields": {
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "dg": {
                                    "integerValue": "1"
                                  },
                                  "akHJ": {
                                    "integerValue": "1"
                                  },
                                  "bahn": {
                                    "integerValue": "2"
                                  },
                                  "name": {
                                    "stringValue": "136388 / KOZAK Jennifer"
                                  },
                                  "kegel": {
                                    "integerValue": "607"
                                  },
                                  "mp": {
                                    "integerValue": "1"
                                  },
                                  "akJahr": {
                                    "integerValue": "1997"
                                  },
                                  "sp": {
                                    "integerValue": "4"
                                  },
                                  "gegner": {
                                    "stringValue": "NIKOLIC Maja Katharina (539)"
                                  }
                                }
                              }
                            },
                            "hzntJDniAMcKDiqC7eS5": {
                              "mapValue": {
                                "fields": {
                                  "akJahr": {
                                    "integerValue": "2006"
                                  },
                                  "akHJ": {
                                    "integerValue": "1"
                                  },
                                  "gegner": {
                                    "stringValue": "PYCHOVA Barbora (550)"
                                  },
                                  "bahn": {
                                    "integerValue": "2"
                                  },
                                  "mp": {
                                    "integerValue": "0"
                                  },
                                  "dg": {
                                    "integerValue": "3"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "name": {
                                    "stringValue": "136054 / BAUMGARTNER Mia-Laura"
                                  },
                                  "sp": {
                                    "integerValue": "2"
                                  },
                                  "kegel": {
                                    "integerValue": "534"
                                  }
                                }
                              }
                            },
                            "6QbEVujH4PLBpdGAOZVi": {
                              "mapValue": {
                                "fields": {
                                  "mp": {
                                    "integerValue": "1"
                                  },
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "dg": {
                                    "integerValue": "3"
                                  },
                                  "sp": {
                                    "integerValue": "3"
                                  },
                                  "name": {
                                    "stringValue": "136135 / STEINER Fiona"
                                  },
                                  "gegner": {
                                    "stringValue": "LAIBACHER Marina (588)"
                                  },
                                  "land": {
                                    "stringValue": "AUT"
                                  },
                                  "kegel": {
                                    "integerValue": "586"
                                  },
                                  "akJahr": {
                                    "integerValue": "1994"
                                  },
                                  "bahn": {
                                    "integerValue": "4"
                                  }
                                }
                              }
                            },
                            "kAp4WMBVaVZmggmUe6Ii": {
                              "mapValue": {
                                "fields": {
                                  "bahn": {
                                    "integerValue": "4"
                                  },
                                  "kegel": {
                                    "integerValue": "648"
                                  },
                                  "mp": {
                                    "integerValue": "1"
                                  },
                                  "gegner": {
                                    "stringValue": "ANGENBAUER Angelika (608)"
                                  },
                                  "dg": {
                                    "integerValue": "1"
                                  },
                                  "akHJ": {
                                    "integerValue": "1"
                                  },
                                  "sp": {
                                    "integerValue": "4"
                                  },
                                  "land": {
                                    "stringValue": "HUN"
                                  },
                                  "akJahr": {
                                    "integerValue": "1998"
                                  },
                                  "name": {
                                    "stringValue": "136384 / HARI Boglarka"
                                  }
                                }
                              }
                            },
                            "c05Wj8GpOVWhxXgLRXIu": {
                              "mapValue": {
                                "fields": {
                                  "akHJ": {
                                    "integerValue": "2"
                                  },
                                  "mp": {
                                    "integerValue": "1"

In [4]:
results = data['fields']['spiele']['mapValue']['fields']
game_keys = list(results.keys())

result_data = pd.DataFrame()

for game in game_keys:
    for location in ['heim', 'gast']:

        players = results[game]['mapValue']['fields'][location]['mapValue']['fields']['spieler']['mapValue']['fields']
        player_keys = list(players.keys())

        for player_key in player_keys:
            player = players[player_key]['mapValue']['fields']
            player_series = pd.json_normalize(player)
            player_series['spieler_id'] = player_key
            player_series['heim'] = location == 'heim'
            player_series['spiel_id'] = game
            result_data = pd.concat([result_data, player_series], ignore_index=True)

result_data

,gegner.stringValue,kegel.integerValue,mp.integerValue,akJahr.integerValue,land.stringValue,name.stringValue,bahn.integerValue,dg.integerValue,akHJ.integerValue,sp.integerValue,spieler_id,heim,spiel_id,mp.doubleValue,sp.doubleValue
0,KOZAK Jennifer (607),539,0,2002,AUT,196408 / NIKOLIC Maja Katharina,1,1,1,0,HFdZhWlRyDDgubstJkvF,True,nKW1HmZZWos39zWU3lhW,NaN,NaN
1,BAUMGARTNER Mia-Laura (534),550,1,2001,CZE,196074 / PYCHOVA Barbora,1,3,2,2,ThGHwnyCP2jPnqAHQ9yA,True,nKW1HmZZWos39zWU3lhW,NaN,NaN
2,STEINER Fiona (586),588,0,1996,AUT,196054 / LAIBACHER Marina,3,3,2,1,yn7rbBEZboGdDw5IfFoM,True,nKW1HmZZWos39zWU3lhW,NaN,NaN
3,NGUYEN Monika (558),568,0,2006,AUT,196411 / STÖCKL Sandra,3,2,2,1,Sm7t0cDy51j4jJuGBKDi,True,nKW1HmZZWos39zWU3lhW,NaN,NaN
4,HARI Boglarka (648),608,0,1991,AUT,196070 / ANGENBAUER Angelika,3,1,2,0,6tFoI6m2UVaXWO2kYZsm,True,nKW1HmZZWos39zWU3lhW,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,LENGAUER Monika (592),543,0,1969,AUT,176026 / HAUSEGGER Andrea,4,1,2,2,1y5AJRx3YjRBg2ZkgmSx,False,BSUfDoHFLTlluYWcQRdl,NaN,NaN
536,MEISTERL Jasmin (586),615,1,2002,AUT,176089 / GSTREIN Franziska,4,2,1,2,2uIGy2DPMwkwdTUMeGvE,False,BSUfDoHFLTlluYWcQRdl,NaN,NaN
537,HAUER Dominique (639),573,0,1999,AUT,176022 / GRUBER Melissa,4,3,1,1,pkZhTZE5WaGWAjCJqRjm,False,BSUfDoHFLTlluYWcQRdl,NaN,NaN
538,EBNER Jessica (541),538,0,1999,ITA,176013 / RABANSER Vera,2,1,2,2,jEdXWyukzwSmGbMHu4Kx,False,BSUfDoHFLTlluYWcQRdl,NaN,NaN
539,PETRU Thea (570),558,0,2007,AUT,176033 / WINDHOFER Sophie,2,2,2,2,J3sZSSnpyrtlyem8hUg2,False,BSUfDoHFLTlluYWcQRdl,NaN,NaN

In [5]:
player_data = result_data.drop_duplicates(subset=['spieler_id'])

player_data = player_data.rename(columns={
    'land.stringValue': 'land',
    'name.stringValue': 'name',
    'akJahr.integerValue': 'jahrgang',
})

player_data = player_data[["spieler_id", "name", "jahrgang", "land"]]
player_data[['passnummer', 'name']] = player_data['name'].str.split(' / ', n=1, expand=True)

player_data.to_csv('player.csv', index=False, sep=';')

In [ ]:
# if integer value is not set, take double value
result_data['sp'] = result_data['sp.integerValue'].fillna(result_data['sp.doubleValue'])
result_data['mp'] = result_data['mp.doubleValue'].fillna(result_data['mp.integerValue'])

results = result_data[["spieler_id", "spiel_id", "kegel.integerValue", "sp", "mp", "heim", "bahn.integerValue", "dg.integerValue"]]
results = results.rename(columns={
    'kegel.integerValue': 'kegel',
    'bahn.integerValue': 'startbahn',
    'dg.integerValue': 'dg',
})

In [7]:
response = requests.get('https://firestore.googleapis.com/v1/projects/oeskb-app/databases/(default)/documents/saisonen/1_8_2024_2025')
data = response.json()
print(json.dumps(data, indent=2))

{
  "name": "projects/oeskb-app/databases/(default)/documents/saisonen/1_8_2024_2025",
  "fields": {
    "sportJahr": {
      "stringValue": "2024_2025"
    },
    "teams": {
      "mapValue": {
        "fields": {
          "3": {
            "mapValue": {
              "fields": {
                "vereinsName": {
                  "stringValue": "KSV Wien"
                },
                "id": {
                  "stringValue": "3"
                },
                "name": {
                  "stringValue": "KSV Wien"
                },
                "lvId": {
                  "stringValue": "19"
                },
                "vereinsNr": {
                  "stringValue": "113"
                }
              }
            }
          },
          "4": {
            "mapValue": {
              "fields": {
                "vereinsNr": {
                  "stringValue": "138"
                },
                "name": {
                  "stringValue": "BSV Voith St. P\u00f6lten"
                },
                "id": {
                  "stringValue": "4"
                },
                "vereinsName": {
                  "stringValue": "BSV Voith St. P\u00f6lten"
                },
                "lvId": {
                  "stringValue": "13"
                }
              }
            }
          },
          "1": {
            "mapValue": {
              "fields": {
                "id": {
                  "stringValue": "1"
                },
                "vereinsName": {
                  "stringValue": "KV SCHWAZ"
                },
                "lvId": {
                  "stringValue": "17"
                },
                "name": {
                  "stringValue": "KV Schwaz"
                },
                "vereinsNr": {
                  "stringValue": "154"
                }
              }
            }
          },
          "9": {
            "mapValue": {
              "fields": {
                "lvId": {
                  "stringValue": "11"
                },
                "id": {
                  "stringValue": "9"
                },
                "vereinsName": {
                  "stringValue": "SKC Kleinwarasdorf"
                },
                "name": {
                  "stringValue": "SKC Kleinwarasdorf"
                },
                "vereinsNr": {
                  "stringValue": "108"
                }
              }
            }
          },
          "8": {
            "mapValue": {
              "fields": {
                "lvId": {
                  "stringValue": "11"
                },
                "vereinsNr": {
                  "stringValue": "110"
                },
                "vereinsName": {
                  "stringValue": "DKV Schlaining"
                },
                "id": {
                  "stringValue": "8"
                },
                "name": {
                  "stringValue": "DKV Schlaining"
                }
              }
            }
          },
          "6": {
            "mapValue": {
              "fields": {
                "name": {
                  "stringValue": "SK FWT-Composites NK"
                },
                "vereinsNr": {
                  "stringValue": "117"
                },
                "id": {
                  "stringValue": "6"
                },
                "lvId": {
                  "stringValue": "13"
                },
                "vereinsName": {
                  "stringValue": "SK FWT-Comp. Neunkirchen"
                }
              }
            }
          },
          "2": {
            "mapValue": {
              "fields": {
                "name": {
                  "stringValue": "BBSV Wien"
                },
                "vereinsNr": {
                  "stringValue": "117"
                },
                "id": {
                  "stringValue": "2"
                },
                "lvId": {
                  "stringValue": "19"
                },
                "vereinsName": {
                  "stringValue": "BBSV Wien"
                }
              }
            }
          },
          "11": {
            "mapValue": {
              "fields": {
                "lvId": {
                  "stringValue": "18"
                },
                "vereinsNr": {
                  "stringValue": "106"
                },
                "vereinsName": {
                  "stringValue": "SG SKC-EHG Dornbirn/ATSV Hard"
                },
                "name": {
                  "stringValue": "SG SKC-EHG Dornbirn / ATSV Hard"
                }
              }
            }
          },
          "5": {
            "mapValue": {
              "fields": {
                "vereinsNr": {
                  "stringValue": "103"
                },
                "name": {
                  "stringValue": "1.KSK Gem.Bed. Wr.Neustadt"
                },
                "id": {
                  "stringValue": "5"
                },
                "vereinsName": {
                  "stringValue": "1.KSK Gem.Bed. Wr.Neustadt"
                },
                "lvId": {
                  "stringValue": "13"
                }
              }
            }
          },
          "10": {
            "mapValue": {
              "fields": {
                "id": {
                  "stringValue": "10"
                },
                "name": {
                  "stringValue": "ASK\u00d6 Steyr Sportkegeln"
                },
                "lvId": {
                  "stringValue": "14"
                },
                "vereinsNr": {
                  "stringValue": "113"
                },
                "vereinsName": {
                  "stringValue": "ASK\u00d6 Steyr Sportkegeln"
                }
              }
            }
          }
        }
      }
    },
    "spiele": {
      "mapValue": {
        "fields": {
          "xLVp8P6ClBhZCVooaubQ": {
            "mapValue": {
              "fields": {
                "heim": {
                  "mapValue": {
                    "fields": {
                      "teamId": {
                        "stringValue": "10"
                      },
                      "result": {
                        "mapValue": {
                          "fields": {
                            "sp": {
                              "doubleValue": 11.5
                            },
                            "mp": {
                              "integerValue": "5"
                            },
                            "tabPkt": {
                              "integerValue": "2"
                            },
                            "oeR": {
                              "booleanValue": false
                            },
                            "kegel": {
                              "integerValue": "3249"
                            },
                            "spielerRecord": {
                              "booleanValue": false
                            },
                            "mR": {
                              "booleanValue": false
                            },
                            "bR": {
                              "booleanValue": false
                            }
                          }
                        }
                      },
                      "teamName": {
                        "stringValue": "ASK\u00d6 Steyr Sportkegeln"
                      },
                      "protest": {
                        "booleanValue": false
                      }
                    }
                  }
                },
                "saison": {
                  "mapValue": {
                    "fields": {
                      "rundeText": {
                        "stringValue": ""
                      },
                      "id": {
                        "stringValue": "1_8_2024_2025"
                      },
                      "runde": {
                        "stringValue": "2"
                      },
                      "semester": {
                        "stringValue": "H"
                      },
                      "freieSpieler": {
                        "booleanValue": false
                      },
                      "lvId": {
                        "stringValue": "1"
                      },
                      "isCup": {
                        "booleanValue": false
                      }
                    }
                  }
                },
                "infos": {
                  "mapValue": {
                    "fields": {
                      "uhrzeit": {
                        "stringValue": "12:00"
                      },
                      "kommentar": {
                        "stringValue": ""
                      },
                      "kommentarStrafe": {
                        "stringValue": ""
                      },
                      "bahn": {
                        "stringValue": "Landeskegelsportzentrum Steyr"
                      },
                      "datum": {
                        "stringValue": "2024-09-15"
                      },
                      "ort": {
                        "stringValue": "Kematm\u00fcllerstrasse 1b, 4400 Steyr"
                      },
                      "wochentag": {
                        "stringValue": "So"
                      },
                      "stream": {
                        "stringValue": "https://www.youtube.com/watch?v=RyPOBoASEmk"
                      }
                    }
                  }
                },
                "vereine": {
                  "mapValue": {
                    "fields": {
                      "gast": {
                        "stringValue": "17154_confirmed"
                      },
                      "confirmedGast": {
                        "integerValue": "1726404031891"
                      },
                      "heim": {
                        "stringValue": "14113_confirmed"
                      },
                      "confirmedHeim": {
                        "integerValue": "1726400535360"
                      }
                    }
                  }
                },
                "gast": {
                  "mapValue": {
                    "fields": {
                      "protest": {
                        "booleanValue": false
                      },
                      "result": {
                        "mapValue": {
                          "fields": {
                            "tabPkt": {
                              "integerValue": "0"
                            },
                            "kegel": {
                              "integerValue": "3212"
                            },
                            "sp": {
                              "doubleValue": 12.5
                            },
                            "mR": {
                              "booleanValue": false
                            },
                            "mp": {
                              "integerValue": "3"
                            },
                            "bR": {
                              "booleanValue": false
                            },
                            "spielerRecord": {
                              "booleanValue": false
                            },
                            "oeR": {
                              "booleanValue": false
                            }
                          }
                        }
                      },
                      "teamName": {
                        "stringValue": "KV Schwaz"
                      },
                      "teamId": {
                        "stringValue": "1"
                      }
                    }
                  }
                },
                "referee": {
                  "mapValue": {
                    "fields": {
                      "name": {
                        "stringValue": "MASIN Elisabeth"
                      }
                    }
                  }
                }
              }
            }
          },
          "oYQRj1hNbsPeGX2f5a1H": {
            "mapValue": {
              "fields": {
                "referee": {
                  "mapValue": {
                    "fields": {
                      "name": {
                        "stringValue": "Valle Reinhold"
                      }
                    }
                  }
                },
                "vereine": {
                  "mapValue": {
                    "fields": {
                      "confirmedHeim": {
                        "integerValue": "1743832611786"
                      },
                      "confirmedGast": {
                        "integerValue": "1743882587762"
                      },
                      "gast": {
                        "stringValue": "13103_confirmed"
                      },
                      "heim": {
                        "stringValue": "17154_confirmed"
                      }
                    }
                  }
                },
                "gast": {
                  "mapValue": {
                    "fields": {
                      "result": {
                        "mapValue": {
                          "fields": {
                            "sp": {
                              "integerValue": "11"
                            },
                            "oeR": {
                              "booleanValue": false
                            },
                            "tabPkt": {
                              "integerValue": "0"
                            },
                            "spielerRecord": {
                              "booleanValue": false
                            },
                            "bR": {
                              "booleanValue": false
                            },
                            "mp": {
                              "integerValue": "3"
                            },
                            "mR": {
                              "booleanValue": false
                            },
                            "kegel": {
                              "integerValue": "3228"
                            }
                          }
                        }
                      },
                      "teamId": {
                        "stringValue": "5"
                      },
                      "protest": {
                        "booleanValue": false
                      },
                      "teamName": {
                        "stringValue": "1.KSK Gem.Bed. Wr.Neustadt"
                      }
                    }
                  }
                },
                "infos": {
                  "mapValue": {
                    "fields": {
                      "bahn": {
                        "stringValue": "Silberstadt Arena"
                      },
                      "kommentarStrafe": {
                        "stringValue": ""
                      },
                      "datum": {
                        "stringValue": "2025-04-05"
                      },
                      "kommentar": {
                        "stringValue": ""
                      },
                      "ort": {
                        "stringValue": "Paulinumweg 2, 6130 Schwaz"
                      },
                      "stream": {
                        "stringValue": "https://www.youtube.com/watch?v=0ALYktAwjlQ"
                      },
                      "uhrzeit": {
                        "stringValue": "10:30"
                      },
                      "wochentag": {
                        "stringValue": "Sa"
                      }
                    }
                  }
                },
                "saison": {
                  "mapValue": {
                    "fields": {
                      "rundeText": {
                        "stringValue": ""
                      },
                      "id": {
                        "stringValue": "1_8_2024_2025"
                      },
                      "semester": {
                        "stringValue": "F"
                      },
                      "freieSpieler": {
                        "booleanValue": false
                      },
                      "isCup": {
                        "booleanValue": false
                      },
                      "lvId": {
                        "stringValue": "1"
                      },
                      "runde": {
                        "stringValue": "9"
                      }
                    }
                  }
                },
                "heim": {
                  "mapValue": {
                    "fields": {
                      "result": {
                        "mapValue": {
                          "fields": {
                            "sp": {
                              "integerValue": "13"
                            },
                            "spielerRecord": {
                              "booleanValue": false
                            },
                            "tabPkt": {
                              "integerValue": "2"
                            },
                            "kegel": {
                              "integerValue": "3229"
                            },
                            "mp": {
                              "integerValue": "5"
                            },
                            "oeR": {
                              "booleanValue": false
                            },
                            "bR": {
                              "booleanValue": false
                            },
                            "mR": {
                              "booleanValue": false
                            }
                          }
                        }
                      },
                      "protest": {
                        "booleanValue": false
                      },
                      "teamName": {
                        "stringValue": "KV Schwaz"
                      },
                      "teamId": {
                        "stringValue": "1"
                      }
                    }
                  }
                }
              }
            }
          },
          "JcMiaxMNmK9kYykDHPnN": {
            "mapValue": {
              "fields": {
                "saison": {
                  "mapValue": {
                    "fields": {
                      "isCup": {
                        "booleanValue": false
                      },
                      "rundeText": {
                        "stringValue": ""
                      },
                      "lvId": {
                        "stringValue": "1"
                      },
                      "id": {
                        "stringValue": "1_8_2024_2025"
                      },
                      "runde": {
                        "stringValue": "2"
                      },
                      "freieSpieler": {
                        "booleanValue": false
                      },
                      "semester": {
                        "stringValue": "F"
                      }
                    }
                  }
                },
                "vereine": {
                  "mapValue": {
                    "fields": {
                      "confirmedGast": {
                        "integerValue": "1737216305119"
                      },
                      "confirmedHeim": {
                        "integerValue": "1737213438134"
                      },
                      "heim": {
                        "stringValue": "19113_confirmed"
                      },
                      "gast": {
                        "stringValue": "18106_confirmed"
                      }
                    }

In [8]:
games = data['fields']['spiele']['mapValue']['fields']
game_keys = list(games.keys())

game_data = pd.DataFrame()

for game_key in game_keys:
    game = games[game_key]["mapValue"]["fields"]["infos"]["mapValue"]["fields"]
    game_series = pd.json_normalize(game)
    game_series['spiel_id'] = game_key
    game_data = pd.concat([game_data, game_series], ignore_index=True)

game_data = game_data.rename(columns={
    'datum.stringValue': 'datum',
    'uhrzeit.stringValue': 'uhrzeit',
    'bahn.stringValue': 'bahn',
})

game_data

game_data = game_data[["datum", "uhrzeit", "bahn", "spiel_id"]]

# concat game data with results
game_data = pd.merge(results, game_data , on='spiel_id', how='left')
game_data

# results.to_csv('game.csv', index=False, sep=';')

,spieler_id,spiel_id,kegel,sp,mp,heim,startbahn,dg,datum,uhrzeit,bahn
0,HFdZhWlRyDDgubstJkvF,nKW1HmZZWos39zWU3lhW,539,0,0,True,1,1,2024-09-28,13:45,KSV Rustenschacherallee
1,ThGHwnyCP2jPnqAHQ9yA,nKW1HmZZWos39zWU3lhW,550,2,1,True,1,3,2024-09-28,13:45,KSV Rustenschacherallee
2,yn7rbBEZboGdDw5IfFoM,nKW1HmZZWos39zWU3lhW,588,1,0,True,3,3,2024-09-28,13:45,KSV Rustenschacherallee
3,Sm7t0cDy51j4jJuGBKDi,nKW1HmZZWos39zWU3lhW,568,1,0,True,3,2,2024-09-28,13:45,KSV Rustenschacherallee
4,6tFoI6m2UVaXWO2kYZsm,nKW1HmZZWos39zWU3lhW,608,0,0,True,3,1,2024-09-28,13:45,KSV Rustenschacherallee
...,...,...,...,...,...,...,...,...,...,...,...
535,1y5AJRx3YjRBg2ZkgmSx,BSUfDoHFLTlluYWcQRdl,543,2,0,False,4,1,2024-11-24,11:00,VSE Sportplatz
536,2uIGy2DPMwkwdTUMeGvE,BSUfDoHFLTlluYWcQRdl,615,2,1,False,4,2,2024-11-24,11:00,VSE Sportplatz
537,pkZhTZE5WaGWAjCJqRjm,BSUfDoHFLTlluYWcQRdl,573,1,0,False,4,3,2024-11-24,11:00,VSE Sportplatz
538,jEdXWyukzwSmGbMHu4Kx,BSUfDoHFLTlluYWcQRdl,538,2,0,False,2,1,2024-11-24,11:00,VSE Sportplatz
539,J3sZSSnpyrtlyem8hUg2,BSUfDoHFLTlluYWcQRdl,558,2,0,False,2,2,2024-11-24,11:00,VSE Sportplatz